### ISSUE TITLE
RIA vs pyradiomics

### ISSUE THREAD

**Issue by isglobal-brge** [cran/RIA#3]
First, thanks for this excellent R package!

I was wondering whether anyone has compared the radiomic features obtained with RIA and pyradiomics ....  should they get the same?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by isglobal-brge** [comment]
Thanks and sorry for the mistake!
